services:
  front:
    image: dimagin/sonar-front:latest
    expose:
      - 8000
    restart: unless-stopped

  nginx:
    container_name: nginx
    restart: unless-stopped
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/conf/:/etc/nginx/conf.d/:ro
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
      - ./app/dist/sonar-front/browser:/usr/share/nginx/html:ro
    depends_on:
      - front

  certbot:
    image: certbot/certbot:latest
    container_name: certbot
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
    command: certonly --webroot -w /var/www/certbot --force-renewal --email ryanfoerster@dimagin.be -d sonarartists.fr --agree-tos
