services:
  sonar-front:
    image: dimagin/sonar-front:latest
    container_name: sonar-front
    ports:
      - "8000:80"
    restart: always
    networks:
      - sonar-network

networks:
  sonar-network:
    driver: bridge
