---
services:
  sonar-front-dev:
    image: dimagin/sonar-front:dev
    container_name: sonar-front-dev
    restart: unless-stopped
    networks:
      - sonar-network-dev
    env_file:
      - .env
    labels:
      - traefik.enable=true
      - traefik.http.routers.sonar-front-dev.entrypoints=web
      - traefik.http.routers.sonar-front-dev.rule=Host(`test.sonarartists.be`)
      - traefik.http.routers.sonar-front-dev.service=sonar-front-dev
      - traefik.http.routers.sonar-front-dev-secure.entrypoints=websecure
      - traefik.http.routers.sonar-front-dev-secure.rule=Host(`test.sonarartists.be`)
      - traefik.http.routers.sonar-front-dev-secure.tls=true
      - traefik.http.routers.sonar-front-dev-secure.service=sonar-front-dev
      - traefik.http.routers.sonar-front-dev-secure.tls.certresolver=cloudflare
      - traefik.http.routers.sonar-front-dev-secure.tls.domains[0].main=test.sonarartists.be
      - traefik.http.routers.sonar-front-dev-secure.tls.domains[0].sans=*.test.sonarartists.be
      - traefik.http.routers.sonar-front-dev-secure.service=api@internal
      - traefik.http.routers.sonar-front-dev-secure.middlewares=traefik-https-redirect

networks:
  sonar-network-dev:
    driver: bridge
  traefik-network:
    external: true
