---
services:
  sonar-front:
    image: dimagin/sonar-front:latest
    container_name: sonar-front
    user: "${UID}:${GID}"
    ports:
      - "${SONAR_FRONTEND_PORT}:80"
    restart: unless-stopped
    networks:
      - sonar-network
    env_file:
      - .env

networks:
  sonar-network:
    driver: bridge
