name: Build and Publish Docker Image

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to docker hub
        id: docker-hub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - name: Build Docker Image
        id: build-image
        run: |
          ls -la
          docker build -t ${{ secrets.DOCKER_USERNAME }}/sonar-front:latest .
      - name: push the docker image
        id: push-image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/sonar-front:latest

      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/sonar-front:latest

      - name: Run the docker container
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            docker stop sonar-front || true
            docker rm sonar-front || true
            docker run -d -p 8070:80 --name sonar-front ${{ secrets.DOCKER_USERNAME }}/sonar-front:latest
