name: Deploy to Production

on:
  workflow_run:
    workflows: ["Build and Publish Docker Image"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Pull the repository
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd sonar-front
            git pull

      - name: Run the docker container
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd sonar-front
            UID=$(id -u) GID=$(id -g) docker compose down
            UID=$(id -u) GID=$(id -g) docker compose pull
            UID=$(id -u) GID=$(id -g) docker compose up -d --force-recreate
