name: Deploy to Production

on:
  workflow_run:
    workflows: ["Build and Publish Docker Image"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Copy the docker-compose file
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_TEST_HOST }}
          username: ${{ secrets.SSH_TEST_USERNAME }}
          password: ${{ secrets.SSH_TEST_PASSWORD }}
          script: |
            cd sonar-front
            curl -o docker-compose.yaml https://raw.githubusercontent.com/${{ github.repository_owner }}/${{ github.event.repository.name }}/main/docker-compose.yaml

      - name: Run the docker container
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_TEST_HOST }}
          username: ${{ secrets.SSH_TEST_USERNAME }}
          password: ${{ secrets.SSH_TEST_PASSWORD }}
          script: |
            cd sonar-front
            docker compose pull
            docker compose down
            docker compose up -d
