name: Deploy to Production

on:
  workflow_run:
    workflows: ["Build and Publish Docker Image"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Pull the Docker image
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/sonar-front:latest

      - name: Run the docker container
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            docker stop sonar-front || true
            docker rm sonar-front || true
            docker run --network=sonar-network -d -p ${{ secrets.SONAR_FRONTEND_PORT }}:80 --name sonar-front ${{ secrets.DOCKER_USERNAME }}/sonar-front:latest
