name: Docker Staging Image

on:
  push:
    branches: ["Ryan"]
  pull_request:
    branches: ["Ryan"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Login to docker hub
        id: docker-hub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

      - name: Build Docker Staging Image
        id: build-image
        run: |
          docker build -f Dockerfile.staging -t ${{ secrets.DOCKER_USERNAME }}/sonar-front:staging .

      - name: Push the Docker Staging Image
        id: push-image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/sonar-front:staging
