name: Build and Publish Docker Image

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to docker hub
        id: docker-hub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - name: Build Docker Image
        id: build-image
        run: |
          ls -la
          docker build -t ${{ secrets.DOCKER_USERNAME }}/sonar-front:latest .
      - name: push the docker image
        id: push-image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/sonar-front:latest

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy the image to the VPS
        run: ssh ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} "docker pull ${{ secrets.DOCKER_USERNAME }}/sonar-front:latest"

      - name: Use Docker Swarm to run the image
        run: ssh ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} "docker service update --image ${{ secrets.DOCKER_USERNAME }}/sonar-front:latest sonar-front"
