name: Build and Push Docker Staging Image to Docker Hub and Deploy to Staging

on:
  push:
    branches: ["Ryan"]
  pull_request:
    branches: ["Ryan"]

jobs:
  build-and-push-docker-staging-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Staging Image to Docker Hub
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile.staging
          tags: ${{ secrets.DOCKER_USERNAME }}/sonar-front:staging
          push: true
          platforms: linux/amd64

  deploy-staging-docker-image:
    needs: build-and-push-docker-staging-image
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Dokploy Deployment
        run: |
          curl -X POST "https://${{ secrets.DOKPLOY_URL }}/api/compose.deploy" \
          -H "accept: application/json" \
          -H "Content-Type: application/json" \
          -H "x-api-key: ${{ secrets.DOKPLOY_STAGING_API_TOKEN }}" \
          -d '{"composeId": "${{ secrets.DOKPLOY_STAGING_COMPOSE_ID }}"}'
